# Generated by Django 5.0.3 on 2024-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
