# Generated by Django 5.0.3 on 2024-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
