# Generated by Django 5.0.3 on 2024-03-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_products_price_alter_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
